'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.5485.
'
Namespace InternetRuiTaiWebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestQueryCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestQueryCode_1OperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestSetCodeConfirmOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestSetCodeCancelOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestConnectDatabase_ShoppingCardOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestConnectDatabase_ActivateCardOperationCompleted As System.Threading.SendOrPostCallback
        
        Private QueryCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetCodeOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = frmMain.sInternetRuiTaiWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler
        
        '''<remarks/>
        Public Event TestQueryCodeCompleted As TestQueryCodeCompletedEventHandler
        
        '''<remarks/>
        Public Event TestQueryCode_1Completed As TestQueryCode_1CompletedEventHandler
        
        '''<remarks/>
        Public Event TestSetCodeConfirmCompleted As TestSetCodeConfirmCompletedEventHandler
        
        '''<remarks/>
        Public Event TestSetCodeCancelCompleted As TestSetCodeCancelCompletedEventHandler
        
        '''<remarks/>
        Public Event TestConnectDatabase_ShoppingCardCompleted As TestConnectDatabase_ShoppingCardCompletedEventHandler
        
        '''<remarks/>
        Public Event TestConnectDatabase_ActivateCardCompleted As TestConnectDatabase_ActivateCardCompletedEventHandler
        
        '''<remarks/>
        Public Event QueryCodeCompleted As QueryCodeCompletedEventHandler
        
        '''<remarks/>
        Public Event SetCodeCompleted As SetCodeCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/HelloWorld", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync()
            Me.HelloWorldAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal userState As Object)
            If (Me.HelloWorldOperationCompleted Is Nothing) Then
                Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
            End If
            Me.InvokeAsync("HelloWorld", New Object(-1) {}, Me.HelloWorldOperationCompleted, userState)
        End Sub
        
        Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
            If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/TestQueryCode", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestQueryCode(ByVal CodePassword As String) As CodeInfoResponse
            Dim results() As Object = Me.Invoke("TestQueryCode", New Object() {CodePassword})
            Return CType(results(0),CodeInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestQueryCodeAsync(ByVal CodePassword As String)
            Me.TestQueryCodeAsync(CodePassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestQueryCodeAsync(ByVal CodePassword As String, ByVal userState As Object)
            If (Me.TestQueryCodeOperationCompleted Is Nothing) Then
                Me.TestQueryCodeOperationCompleted = AddressOf Me.OnTestQueryCodeOperationCompleted
            End If
            Me.InvokeAsync("TestQueryCode", New Object() {CodePassword}, Me.TestQueryCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestQueryCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestQueryCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestQueryCodeCompleted(Me, New TestQueryCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/TestQueryCode_1", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestQueryCode_1() As CodeInfoResponse
            Dim results() As Object = Me.Invoke("TestQueryCode_1", New Object(-1) {})
            Return CType(results(0),CodeInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestQueryCode_1Async()
            Me.TestQueryCode_1Async(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestQueryCode_1Async(ByVal userState As Object)
            If (Me.TestQueryCode_1OperationCompleted Is Nothing) Then
                Me.TestQueryCode_1OperationCompleted = AddressOf Me.OnTestQueryCode_1OperationCompleted
            End If
            Me.InvokeAsync("TestQueryCode_1", New Object(-1) {}, Me.TestQueryCode_1OperationCompleted, userState)
        End Sub
        
        Private Sub OnTestQueryCode_1OperationCompleted(ByVal arg As Object)
            If (Not (Me.TestQueryCode_1CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestQueryCode_1Completed(Me, New TestQueryCode_1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/TestSetCodeConfirm", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestSetCodeConfirm(ByVal CodePassword As String) As SetCodeInfoResponse
            Dim results() As Object = Me.Invoke("TestSetCodeConfirm", New Object() {CodePassword})
            Return CType(results(0),SetCodeInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestSetCodeConfirmAsync(ByVal CodePassword As String)
            Me.TestSetCodeConfirmAsync(CodePassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestSetCodeConfirmAsync(ByVal CodePassword As String, ByVal userState As Object)
            If (Me.TestSetCodeConfirmOperationCompleted Is Nothing) Then
                Me.TestSetCodeConfirmOperationCompleted = AddressOf Me.OnTestSetCodeConfirmOperationCompleted
            End If
            Me.InvokeAsync("TestSetCodeConfirm", New Object() {CodePassword}, Me.TestSetCodeConfirmOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestSetCodeConfirmOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestSetCodeConfirmCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestSetCodeConfirmCompleted(Me, New TestSetCodeConfirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/TestSetCodeCancel", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestSetCodeCancel(ByVal CodePassword As String) As SetCodeInfoResponse
            Dim results() As Object = Me.Invoke("TestSetCodeCancel", New Object() {CodePassword})
            Return CType(results(0),SetCodeInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestSetCodeCancelAsync(ByVal CodePassword As String)
            Me.TestSetCodeCancelAsync(CodePassword, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestSetCodeCancelAsync(ByVal CodePassword As String, ByVal userState As Object)
            If (Me.TestSetCodeCancelOperationCompleted Is Nothing) Then
                Me.TestSetCodeCancelOperationCompleted = AddressOf Me.OnTestSetCodeCancelOperationCompleted
            End If
            Me.InvokeAsync("TestSetCodeCancel", New Object() {CodePassword}, Me.TestSetCodeCancelOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestSetCodeCancelOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestSetCodeCancelCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestSetCodeCancelCompleted(Me, New TestSetCodeCancelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/TestConnectDatabase_ShoppingCard", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestConnectDatabase_ShoppingCard() As String
            Dim results() As Object = Me.Invoke("TestConnectDatabase_ShoppingCard", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestConnectDatabase_ShoppingCardAsync()
            Me.TestConnectDatabase_ShoppingCardAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestConnectDatabase_ShoppingCardAsync(ByVal userState As Object)
            If (Me.TestConnectDatabase_ShoppingCardOperationCompleted Is Nothing) Then
                Me.TestConnectDatabase_ShoppingCardOperationCompleted = AddressOf Me.OnTestConnectDatabase_ShoppingCardOperationCompleted
            End If
            Me.InvokeAsync("TestConnectDatabase_ShoppingCard", New Object(-1) {}, Me.TestConnectDatabase_ShoppingCardOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestConnectDatabase_ShoppingCardOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestConnectDatabase_ShoppingCardCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestConnectDatabase_ShoppingCardCompleted(Me, New TestConnectDatabase_ShoppingCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/TestConnectDatabase_ActivateCard", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestConnectDatabase_ActivateCard() As String
            Dim results() As Object = Me.Invoke("TestConnectDatabase_ActivateCard", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestConnectDatabase_ActivateCardAsync()
            Me.TestConnectDatabase_ActivateCardAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestConnectDatabase_ActivateCardAsync(ByVal userState As Object)
            If (Me.TestConnectDatabase_ActivateCardOperationCompleted Is Nothing) Then
                Me.TestConnectDatabase_ActivateCardOperationCompleted = AddressOf Me.OnTestConnectDatabase_ActivateCardOperationCompleted
            End If
            Me.InvokeAsync("TestConnectDatabase_ActivateCard", New Object(-1) {}, Me.TestConnectDatabase_ActivateCardOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestConnectDatabase_ActivateCardOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestConnectDatabase_ActivateCardCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestConnectDatabase_ActivateCardCompleted(Me, New TestConnectDatabase_ActivateCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/QueryCode", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function QueryCode(ByVal CClass As CodeInfo) As CodeInfoResponse
            Dim results() As Object = Me.Invoke("QueryCode", New Object() {CClass})
            Return CType(results(0),CodeInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub QueryCodeAsync(ByVal CClass As CodeInfo)
            Me.QueryCodeAsync(CClass, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub QueryCodeAsync(ByVal CClass As CodeInfo, ByVal userState As Object)
            If (Me.QueryCodeOperationCompleted Is Nothing) Then
                Me.QueryCodeOperationCompleted = AddressOf Me.OnQueryCodeOperationCompleted
            End If
            Me.InvokeAsync("QueryCode", New Object() {CClass}, Me.QueryCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnQueryCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.QueryCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent QueryCodeCompleted(Me, New QueryCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://microsoft.com/webservices/SetCode", RequestNamespace:="http://microsoft.com/webservices/", ResponseNamespace:="http://microsoft.com/webservices/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SetCode(ByVal CClass As SetCodeInfo, ByVal GClass As GuIDClass) As SetCodeInfoResponse
            Dim results() As Object = Me.Invoke("SetCode", New Object() {CClass, GClass})
            Return CType(results(0),SetCodeInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SetCodeAsync(ByVal CClass As SetCodeInfo, ByVal GClass As GuIDClass)
            Me.SetCodeAsync(CClass, GClass, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetCodeAsync(ByVal CClass As SetCodeInfo, ByVal GClass As GuIDClass, ByVal userState As Object)
            If (Me.SetCodeOperationCompleted Is Nothing) Then
                Me.SetCodeOperationCompleted = AddressOf Me.OnSetCodeOperationCompleted
            End If
            Me.InvokeAsync("SetCode", New Object() {CClass, GClass}, Me.SetCodeOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetCodeOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetCodeCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetCodeCompleted(Me, New SetCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class CodeInfoResponse
        
        Private codeMsgField As CodeMsg
        
        Private codePasswordField As String
        
        Private codeAmountField As String
        
        Private discountTotalField As String
        
        Private flowIdField As String
        
        Private serialNoField As String
        
        Private sponsorField As String
        
        Private notesField As String
        
        Private codeTypeField As String
        
        Private validDateField As String
        
        '''<remarks/>
        Public Property CodeMsg() As CodeMsg
            Get
                Return Me.codeMsgField
            End Get
            Set
                Me.codeMsgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodePassword() As String
            Get
                Return Me.codePasswordField
            End Get
            Set
                Me.codePasswordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodeAmount() As String
            Get
                Return Me.codeAmountField
            End Get
            Set
                Me.codeAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DiscountTotal() As String
            Get
                Return Me.discountTotalField
            End Get
            Set
                Me.discountTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FlowId() As String
            Get
                Return Me.flowIdField
            End Get
            Set
                Me.flowIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SerialNo() As String
            Get
                Return Me.serialNoField
            End Get
            Set
                Me.serialNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sponsor() As String
            Get
                Return Me.sponsorField
            End Get
            Set
                Me.sponsorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Notes() As String
            Get
                Return Me.notesField
            End Get
            Set
                Me.notesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodeType() As String
            Get
                Return Me.codeTypeField
            End Get
            Set
                Me.codeTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ValidDate() As String
            Get
                Return Me.validDateField
            End Get
            Set
                Me.validDateField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class CodeMsg
        
        Private codeField As String
        
        Private msgField As String
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Msg() As String
            Get
                Return Me.msgField
            End Get
            Set
                Me.msgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class GuIDClass
        
        Private guIDField As String
        
        '''<remarks/>
        Public Property GuID() As String
            Get
                Return Me.guIDField
            End Get
            Set
                Me.guIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class SetCodeInfo
        
        Private groupIdField As String
        
        Private shopIdField As String
        
        Private posIdField As String
        
        Private accountField As String
        
        Private passwdField As String
        
        Private operTypeField As String
        
        Private flowIdField As String
        
        Private serialNoField As String
        
        Private codePasswordField As String
        
        Private confirmAmountField As String
        
        Private keyField As String
        
        Private signField As String
        
        '''<remarks/>
        Public Property GroupId() As String
            Get
                Return Me.groupIdField
            End Get
            Set
                Me.groupIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShopId() As String
            Get
                Return Me.shopIdField
            End Get
            Set
                Me.shopIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PosId() As String
            Get
                Return Me.posIdField
            End Get
            Set
                Me.posIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Account() As String
            Get
                Return Me.accountField
            End Get
            Set
                Me.accountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Passwd() As String
            Get
                Return Me.passwdField
            End Get
            Set
                Me.passwdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OperType() As String
            Get
                Return Me.operTypeField
            End Get
            Set
                Me.operTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FlowId() As String
            Get
                Return Me.flowIdField
            End Get
            Set
                Me.flowIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SerialNo() As String
            Get
                Return Me.serialNoField
            End Get
            Set
                Me.serialNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodePassword() As String
            Get
                Return Me.codePasswordField
            End Get
            Set
                Me.codePasswordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ConfirmAmount() As String
            Get
                Return Me.confirmAmountField
            End Get
            Set
                Me.confirmAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sign() As String
            Get
                Return Me.signField
            End Get
            Set
                Me.signField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class CodeInfo
        
        Private groupIdField As String
        
        Private shopIdField As String
        
        Private posIdField As String
        
        Private accountField As String
        
        Private passwdField As String
        
        Private flowIdField As String
        
        Private serialNoField As String
        
        Private codePasswordField As String
        
        Private keyField As String
        
        Private dealAmountTotalField As String
        
        Private dealDateField As String
        
        Private signField As String
        
        '''<remarks/>
        Public Property GroupId() As String
            Get
                Return Me.groupIdField
            End Get
            Set
                Me.groupIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ShopId() As String
            Get
                Return Me.shopIdField
            End Get
            Set
                Me.shopIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PosId() As String
            Get
                Return Me.posIdField
            End Get
            Set
                Me.posIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Account() As String
            Get
                Return Me.accountField
            End Get
            Set
                Me.accountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Passwd() As String
            Get
                Return Me.passwdField
            End Get
            Set
                Me.passwdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property FlowId() As String
            Get
                Return Me.flowIdField
            End Get
            Set
                Me.flowIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SerialNo() As String
            Get
                Return Me.serialNoField
            End Get
            Set
                Me.serialNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CodePassword() As String
            Get
                Return Me.codePasswordField
            End Get
            Set
                Me.codePasswordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DealAmountTotal() As String
            Get
                Return Me.dealAmountTotalField
            End Get
            Set
                Me.dealAmountTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DealDate() As String
            Get
                Return Me.dealDateField
            End Get
            Set
                Me.dealDateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Sign() As String
            Get
                Return Me.signField
            End Get
            Set
                Me.signField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5485"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://microsoft.com/webservices/")>  _
    Partial Public Class SetCodeInfoResponse
        
        Private codeMsgField As CodeMsg
        
        Private serialNoField As String
        
        Private dealIdField As String
        
        '''<remarks/>
        Public Property CodeMsg() As CodeMsg
            Get
                Return Me.codeMsgField
            End Get
            Set
                Me.codeMsgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SerialNo() As String
            Get
                Return Me.serialNoField
            End Get
            Set
                Me.serialNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DealId() As String
            Get
                Return Me.dealIdField
            End Get
            Set
                Me.dealIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HelloWorldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub TestQueryCodeCompletedEventHandler(ByVal sender As Object, ByVal e As TestQueryCodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TestQueryCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CodeInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CodeInfoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub TestQueryCode_1CompletedEventHandler(ByVal sender As Object, ByVal e As TestQueryCode_1CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TestQueryCode_1CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CodeInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CodeInfoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub TestSetCodeConfirmCompletedEventHandler(ByVal sender As Object, ByVal e As TestSetCodeConfirmCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TestSetCodeConfirmCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SetCodeInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SetCodeInfoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub TestSetCodeCancelCompletedEventHandler(ByVal sender As Object, ByVal e As TestSetCodeCancelCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TestSetCodeCancelCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SetCodeInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SetCodeInfoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub TestConnectDatabase_ShoppingCardCompletedEventHandler(ByVal sender As Object, ByVal e As TestConnectDatabase_ShoppingCardCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TestConnectDatabase_ShoppingCardCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub TestConnectDatabase_ActivateCardCompletedEventHandler(ByVal sender As Object, ByVal e As TestConnectDatabase_ActivateCardCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TestConnectDatabase_ActivateCardCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub QueryCodeCompletedEventHandler(ByVal sender As Object, ByVal e As QueryCodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class QueryCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CodeInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CodeInfoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub SetCodeCompletedEventHandler(ByVal sender As Object, ByVal e As SetCodeCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SetCodeCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As SetCodeInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),SetCodeInfoResponse)
            End Get
        End Property
    End Class
End Namespace
