'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8762
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.8762.
'
Namespace InternetWebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HelloWorldOperationCompleted As System.Threading.SendOrPostCallback
        
        Private QueryExtractingCodeInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private QueryExtractingCodeInfoTestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetExtractingCodeStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private SetExtractingCodeUsedUpdateStatusOperationCompleted As System.Threading.SendOrPostCallback
        
        Private QueryOrderAllInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private QueryOrderAllInfoTestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = frmMain.sInternetWebService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HelloWorldCompleted As HelloWorldCompletedEventHandler
        
        '''<remarks/>
        Public Event QueryExtractingCodeInfoCompleted As QueryExtractingCodeInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event QueryExtractingCodeInfoTestCompleted As QueryExtractingCodeInfoTestCompletedEventHandler
        
        '''<remarks/>
        Public Event SetExtractingCodeStatusCompleted As SetExtractingCodeStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event SetExtractingCodeUsedUpdateStatusCompleted As SetExtractingCodeUsedUpdateStatusCompletedEventHandler
        
        '''<remarks/>
        Public Event QueryOrderAllInfoCompleted As QueryOrderAllInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event QueryOrderAllInfoTestCompleted As QueryOrderAllInfoTestCompletedEventHandler
        
        '''<remarks/>
        Public Event TestRequestCompleted As TestRequestCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HelloWorld() As String
            Dim results() As Object = Me.Invoke("HelloWorld", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync()
            Me.HelloWorldAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HelloWorldAsync(ByVal userState As Object)
            If (Me.HelloWorldOperationCompleted Is Nothing) Then
                Me.HelloWorldOperationCompleted = AddressOf Me.OnHelloWorldOperationCompleted
            End If
            Me.InvokeAsync("HelloWorld", New Object(-1) {}, Me.HelloWorldOperationCompleted, userState)
        End Sub
        
        Private Sub OnHelloWorldOperationCompleted(ByVal arg As Object)
            If (Not (Me.HelloWorldCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HelloWorldCompleted(Me, New HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryExtractingCodeInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function QueryExtractingCodeInfo(ByVal CClass As ExtractingCodeInfo) As ExtractingCodeInfoResponse
            Dim results() As Object = Me.Invoke("QueryExtractingCodeInfo", New Object() {CClass})
            Return CType(results(0),ExtractingCodeInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub QueryExtractingCodeInfoAsync(ByVal CClass As ExtractingCodeInfo)
            Me.QueryExtractingCodeInfoAsync(CClass, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub QueryExtractingCodeInfoAsync(ByVal CClass As ExtractingCodeInfo, ByVal userState As Object)
            If (Me.QueryExtractingCodeInfoOperationCompleted Is Nothing) Then
                Me.QueryExtractingCodeInfoOperationCompleted = AddressOf Me.OnQueryExtractingCodeInfoOperationCompleted
            End If
            Me.InvokeAsync("QueryExtractingCodeInfo", New Object() {CClass}, Me.QueryExtractingCodeInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnQueryExtractingCodeInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.QueryExtractingCodeInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent QueryExtractingCodeInfoCompleted(Me, New QueryExtractingCodeInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryExtractingCodeInfoTest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function QueryExtractingCodeInfoTest(ByVal sIssuerId As String, ByVal sMobilePhone As String, ByVal sExtractingCode As String) As ExtractingCodeInfoResponse
            Dim results() As Object = Me.Invoke("QueryExtractingCodeInfoTest", New Object() {sIssuerId, sMobilePhone, sExtractingCode})
            Return CType(results(0),ExtractingCodeInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub QueryExtractingCodeInfoTestAsync(ByVal sIssuerId As String, ByVal sMobilePhone As String, ByVal sExtractingCode As String)
            Me.QueryExtractingCodeInfoTestAsync(sIssuerId, sMobilePhone, sExtractingCode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub QueryExtractingCodeInfoTestAsync(ByVal sIssuerId As String, ByVal sMobilePhone As String, ByVal sExtractingCode As String, ByVal userState As Object)
            If (Me.QueryExtractingCodeInfoTestOperationCompleted Is Nothing) Then
                Me.QueryExtractingCodeInfoTestOperationCompleted = AddressOf Me.OnQueryExtractingCodeInfoTestOperationCompleted
            End If
            Me.InvokeAsync("QueryExtractingCodeInfoTest", New Object() {sIssuerId, sMobilePhone, sExtractingCode}, Me.QueryExtractingCodeInfoTestOperationCompleted, userState)
        End Sub
        
        Private Sub OnQueryExtractingCodeInfoTestOperationCompleted(ByVal arg As Object)
            If (Not (Me.QueryExtractingCodeInfoTestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent QueryExtractingCodeInfoTestCompleted(Me, New QueryExtractingCodeInfoTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetExtractingCodeStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SetExtractingCodeStatus(ByVal CClass As SetExtractingCodeStatus, ByVal GClass As GuIDClass) As CodeMsg
            Dim results() As Object = Me.Invoke("SetExtractingCodeStatus", New Object() {CClass, GClass})
            Return CType(results(0),CodeMsg)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SetExtractingCodeStatusAsync(ByVal CClass As SetExtractingCodeStatus, ByVal GClass As GuIDClass)
            Me.SetExtractingCodeStatusAsync(CClass, GClass, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetExtractingCodeStatusAsync(ByVal CClass As SetExtractingCodeStatus, ByVal GClass As GuIDClass, ByVal userState As Object)
            If (Me.SetExtractingCodeStatusOperationCompleted Is Nothing) Then
                Me.SetExtractingCodeStatusOperationCompleted = AddressOf Me.OnSetExtractingCodeStatusOperationCompleted
            End If
            Me.InvokeAsync("SetExtractingCodeStatus", New Object() {CClass, GClass}, Me.SetExtractingCodeStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetExtractingCodeStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetExtractingCodeStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetExtractingCodeStatusCompleted(Me, New SetExtractingCodeStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SetExtractingCodeUsedUpdateStatus", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function SetExtractingCodeUsedUpdateStatus(ByVal CClass As SetExtractingCodeUsedUpdateStatus, ByVal GClass As GuIDClass) As CodeMsg
            Dim results() As Object = Me.Invoke("SetExtractingCodeUsedUpdateStatus", New Object() {CClass, GClass})
            Return CType(results(0),CodeMsg)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SetExtractingCodeUsedUpdateStatusAsync(ByVal CClass As SetExtractingCodeUsedUpdateStatus, ByVal GClass As GuIDClass)
            Me.SetExtractingCodeUsedUpdateStatusAsync(CClass, GClass, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SetExtractingCodeUsedUpdateStatusAsync(ByVal CClass As SetExtractingCodeUsedUpdateStatus, ByVal GClass As GuIDClass, ByVal userState As Object)
            If (Me.SetExtractingCodeUsedUpdateStatusOperationCompleted Is Nothing) Then
                Me.SetExtractingCodeUsedUpdateStatusOperationCompleted = AddressOf Me.OnSetExtractingCodeUsedUpdateStatusOperationCompleted
            End If
            Me.InvokeAsync("SetExtractingCodeUsedUpdateStatus", New Object() {CClass, GClass}, Me.SetExtractingCodeUsedUpdateStatusOperationCompleted, userState)
        End Sub
        
        Private Sub OnSetExtractingCodeUsedUpdateStatusOperationCompleted(ByVal arg As Object)
            If (Not (Me.SetExtractingCodeUsedUpdateStatusCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SetExtractingCodeUsedUpdateStatusCompleted(Me, New SetExtractingCodeUsedUpdateStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryOrderAllInfo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function QueryOrderAllInfo(ByVal CClass As OrderAllInfo) As OrderAllInfoResponse
            Dim results() As Object = Me.Invoke("QueryOrderAllInfo", New Object() {CClass})
            Return CType(results(0),OrderAllInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub QueryOrderAllInfoAsync(ByVal CClass As OrderAllInfo)
            Me.QueryOrderAllInfoAsync(CClass, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub QueryOrderAllInfoAsync(ByVal CClass As OrderAllInfo, ByVal userState As Object)
            If (Me.QueryOrderAllInfoOperationCompleted Is Nothing) Then
                Me.QueryOrderAllInfoOperationCompleted = AddressOf Me.OnQueryOrderAllInfoOperationCompleted
            End If
            Me.InvokeAsync("QueryOrderAllInfo", New Object() {CClass}, Me.QueryOrderAllInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnQueryOrderAllInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.QueryOrderAllInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent QueryOrderAllInfoCompleted(Me, New QueryOrderAllInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/QueryOrderAllInfoTest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function QueryOrderAllInfoTest(ByVal sIssuerId As String, ByVal sBillNo As String) As OrderAllInfoResponse
            Dim results() As Object = Me.Invoke("QueryOrderAllInfoTest", New Object() {sIssuerId, sBillNo})
            Return CType(results(0),OrderAllInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub QueryOrderAllInfoTestAsync(ByVal sIssuerId As String, ByVal sBillNo As String)
            Me.QueryOrderAllInfoTestAsync(sIssuerId, sBillNo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub QueryOrderAllInfoTestAsync(ByVal sIssuerId As String, ByVal sBillNo As String, ByVal userState As Object)
            If (Me.QueryOrderAllInfoTestOperationCompleted Is Nothing) Then
                Me.QueryOrderAllInfoTestOperationCompleted = AddressOf Me.OnQueryOrderAllInfoTestOperationCompleted
            End If
            Me.InvokeAsync("QueryOrderAllInfoTest", New Object() {sIssuerId, sBillNo}, Me.QueryOrderAllInfoTestOperationCompleted, userState)
        End Sub
        
        Private Sub OnQueryOrderAllInfoTestOperationCompleted(ByVal arg As Object)
            If (Not (Me.QueryOrderAllInfoTestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent QueryOrderAllInfoTestCompleted(Me, New QueryOrderAllInfoTestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestRequest", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function TestRequest() As OrderAllInfoResponse
            Dim results() As Object = Me.Invoke("TestRequest", New Object(-1) {})
            Return CType(results(0),OrderAllInfoResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TestRequestAsync()
            Me.TestRequestAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestRequestAsync(ByVal userState As Object)
            If (Me.TestRequestOperationCompleted Is Nothing) Then
                Me.TestRequestOperationCompleted = AddressOf Me.OnTestRequestOperationCompleted
            End If
            Me.InvokeAsync("TestRequest", New Object(-1) {}, Me.TestRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestRequestCompleted(Me, New TestRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ExtractingCodeInfo
        
        Private issuerIdField As String
        
        Private mobilePhoneField As String
        
        Private extractingCodeField As String
        
        Private macField As String
        
        Private typeField As String
        
        '''<remarks/>
        Public Property IssuerId() As String
            Get
                Return Me.issuerIdField
            End Get
            Set
                Me.issuerIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MobilePhone() As String
            Get
                Return Me.mobilePhoneField
            End Get
            Set
                Me.mobilePhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExtractingCode() As String
            Get
                Return Me.extractingCodeField
            End Get
            Set
                Me.extractingCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mac() As String
            Get
                Return Me.macField
            End Get
            Set
                Me.macField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CardTransInfo
        
        Private cardNoField As String
        
        Private cardHolderMobileField As String
        
        Private amountField As String
        
        Private payAmountField As String
        
        Private areaCodeField As String
        
        Private productIdField As String
        
        Private productNameField As String
        
        Private productNumField As String
        
        Private promotionAmountField As String
        
        '''<remarks/>
        Public Property CardNo() As String
            Get
                Return Me.cardNoField
            End Get
            Set
                Me.cardNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CardHolderMobile() As String
            Get
                Return Me.cardHolderMobileField
            End Get
            Set
                Me.cardHolderMobileField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Amount() As String
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PayAmount() As String
            Get
                Return Me.payAmountField
            End Get
            Set
                Me.payAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AreaCode() As String
            Get
                Return Me.areaCodeField
            End Get
            Set
                Me.areaCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProductId() As String
            Get
                Return Me.productIdField
            End Get
            Set
                Me.productIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProductName() As String
            Get
                Return Me.productNameField
            End Get
            Set
                Me.productNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProductNum() As String
            Get
                Return Me.productNumField
            End Get
            Set
                Me.productNumField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PromotionAmount() As String
            Get
                Return Me.promotionAmountField
            End Get
            Set
                Me.promotionAmountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class OrderAllInfoData
        
        Private cardTransInfoArrayField() As CardTransInfo
        
        Private issuerIdField As String
        
        Private billNoField As String
        
        Private billTotalAmountField As String
        
        Private billPayTotalAmountField As String
        
        Private billTotalNumField As String
        
        Private billPayStatusField As String
        
        Private billTypeField As String
        
        Private billCreateTimestampField As String
        
        Private billBuyChannelField As String
        
        Private buyerMobilePhoneField As String
        
        Private holderMobilePhoneField As String
        
        Private createTimeField As String
        
        Private updateTimeField As String
        
        '''<remarks/>
        Public Property CardTransInfoArray() As CardTransInfo()
            Get
                Return Me.cardTransInfoArrayField
            End Get
            Set
                Me.cardTransInfoArrayField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IssuerId() As String
            Get
                Return Me.issuerIdField
            End Get
            Set
                Me.issuerIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillNo() As String
            Get
                Return Me.billNoField
            End Get
            Set
                Me.billNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillTotalAmount() As String
            Get
                Return Me.billTotalAmountField
            End Get
            Set
                Me.billTotalAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillPayTotalAmount() As String
            Get
                Return Me.billPayTotalAmountField
            End Get
            Set
                Me.billPayTotalAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillTotalNum() As String
            Get
                Return Me.billTotalNumField
            End Get
            Set
                Me.billTotalNumField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillPayStatus() As String
            Get
                Return Me.billPayStatusField
            End Get
            Set
                Me.billPayStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillType() As String
            Get
                Return Me.billTypeField
            End Get
            Set
                Me.billTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillCreateTimestamp() As String
            Get
                Return Me.billCreateTimestampField
            End Get
            Set
                Me.billCreateTimestampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillBuyChannel() As String
            Get
                Return Me.billBuyChannelField
            End Get
            Set
                Me.billBuyChannelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BuyerMobilePhone() As String
            Get
                Return Me.buyerMobilePhoneField
            End Get
            Set
                Me.buyerMobilePhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HolderMobilePhone() As String
            Get
                Return Me.holderMobilePhoneField
            End Get
            Set
                Me.holderMobilePhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreateTime() As String
            Get
                Return Me.createTimeField
            End Get
            Set
                Me.createTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdateTime() As String
            Get
                Return Me.updateTimeField
            End Get
            Set
                Me.updateTimeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class OrderAllInfoResponse
        
        Private codeMsgField As CodeMsg
        
        Private orderAllInfoDataField As OrderAllInfoData
        
        '''<remarks/>
        Public Property CodeMsg() As CodeMsg
            Get
                Return Me.codeMsgField
            End Get
            Set
                Me.codeMsgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property OrderAllInfoData() As OrderAllInfoData
            Get
                Return Me.orderAllInfoDataField
            End Get
            Set
                Me.orderAllInfoDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class CodeMsg
        
        Private codeField As String
        
        Private msgField As String
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Msg() As String
            Get
                Return Me.msgField
            End Get
            Set
                Me.msgField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class OrderAllInfo
        
        Private issuerIdField As String
        
        Private billNoField As String
        
        Private macField As String
        
        Private typeField As String
        
        '''<remarks/>
        Public Property IssuerId() As String
            Get
                Return Me.issuerIdField
            End Get
            Set
                Me.issuerIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillNo() As String
            Get
                Return Me.billNoField
            End Get
            Set
                Me.billNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mac() As String
            Get
                Return Me.macField
            End Get
            Set
                Me.macField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetExtractingCodeUsedUpdateStatus
        
        Private issuerIdField As String
        
        Private mobilePhoneField As String
        
        Private extractingCodeField As String
        
        Private moteStatusField As String
        
        Private cardsField As String
        
        Private macField As String
        
        Private typeField As String
        
        '''<remarks/>
        Public Property IssuerId() As String
            Get
                Return Me.issuerIdField
            End Get
            Set
                Me.issuerIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MobilePhone() As String
            Get
                Return Me.mobilePhoneField
            End Get
            Set
                Me.mobilePhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExtractingCode() As String
            Get
                Return Me.extractingCodeField
            End Get
            Set
                Me.extractingCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MoteStatus() As String
            Get
                Return Me.moteStatusField
            End Get
            Set
                Me.moteStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cards() As String
            Get
                Return Me.cardsField
            End Get
            Set
                Me.cardsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mac() As String
            Get
                Return Me.macField
            End Get
            Set
                Me.macField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GuIDClass
        
        Private guIDField As String
        
        '''<remarks/>
        Public Property GuID() As String
            Get
                Return Me.guIDField
            End Get
            Set
                Me.guIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetExtractingCodeStatus
        
        Private issuerIdField As String
        
        Private mobilePhoneField As String
        
        Private extractingCodeField As String
        
        Private cardsField As String
        
        Private macField As String
        
        Private typeField As String
        
        '''<remarks/>
        Public Property IssuerId() As String
            Get
                Return Me.issuerIdField
            End Get
            Set
                Me.issuerIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MobilePhone() As String
            Get
                Return Me.mobilePhoneField
            End Get
            Set
                Me.mobilePhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExtractingCode() As String
            Get
                Return Me.extractingCodeField
            End Get
            Set
                Me.extractingCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cards() As String
            Get
                Return Me.cardsField
            End Get
            Set
                Me.cardsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Mac() As String
            Get
                Return Me.macField
            End Get
            Set
                Me.macField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ExtractingCodeInfoDetailData
        
        Private productIdField As String
        
        Private areaCodeField As String
        
        Private productNameField As String
        
        Private statusField As String
        
        Private cardPriceField As String
        
        Private productNumField As String
        
        Private payAmountField As String
        
        '''<remarks/>
        Public Property ProductId() As String
            Get
                Return Me.productIdField
            End Get
            Set
                Me.productIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AreaCode() As String
            Get
                Return Me.areaCodeField
            End Get
            Set
                Me.areaCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProductName() As String
            Get
                Return Me.productNameField
            End Get
            Set
                Me.productNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CardPrice() As String
            Get
                Return Me.cardPriceField
            End Get
            Set
                Me.cardPriceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ProductNum() As String
            Get
                Return Me.productNumField
            End Get
            Set
                Me.productNumField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PayAmount() As String
            Get
                Return Me.payAmountField
            End Get
            Set
                Me.payAmountField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ExtractingCodeInfoData
        
        Private extractingCodeField As String
        
        Private statusField As String
        
        Private hotReasonField As String
        
        Private issuerIdField As String
        
        Private billNoField As String
        
        Private billTotalAmountField As String
        
        Private billPayTotalAmountField As String
        
        Private billTotalNumField As String
        
        Private billPayStatusField As String
        
        Private billTypeField As String
        
        Private billCreateTimestampField As String
        
        Private billBuyChannelField As String
        
        Private buyerMobilePhoneField As String
        
        Private holderMobilePhoneField As String
        
        Private createTimeField As String
        
        Private updateTimeField As String
        
        Private extractingCodeInfoDetailDataField As ExtractingCodeInfoDetailData
        
        '''<remarks/>
        Public Property ExtractingCode() As String
            Get
                Return Me.extractingCodeField
            End Get
            Set
                Me.extractingCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As String
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HotReason() As String
            Get
                Return Me.hotReasonField
            End Get
            Set
                Me.hotReasonField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property IssuerId() As String
            Get
                Return Me.issuerIdField
            End Get
            Set
                Me.issuerIdField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillNo() As String
            Get
                Return Me.billNoField
            End Get
            Set
                Me.billNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillTotalAmount() As String
            Get
                Return Me.billTotalAmountField
            End Get
            Set
                Me.billTotalAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillPayTotalAmount() As String
            Get
                Return Me.billPayTotalAmountField
            End Get
            Set
                Me.billPayTotalAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillTotalNum() As String
            Get
                Return Me.billTotalNumField
            End Get
            Set
                Me.billTotalNumField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillPayStatus() As String
            Get
                Return Me.billPayStatusField
            End Get
            Set
                Me.billPayStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillType() As String
            Get
                Return Me.billTypeField
            End Get
            Set
                Me.billTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillCreateTimestamp() As String
            Get
                Return Me.billCreateTimestampField
            End Get
            Set
                Me.billCreateTimestampField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BillBuyChannel() As String
            Get
                Return Me.billBuyChannelField
            End Get
            Set
                Me.billBuyChannelField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property BuyerMobilePhone() As String
            Get
                Return Me.buyerMobilePhoneField
            End Get
            Set
                Me.buyerMobilePhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property HolderMobilePhone() As String
            Get
                Return Me.holderMobilePhoneField
            End Get
            Set
                Me.holderMobilePhoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CreateTime() As String
            Get
                Return Me.createTimeField
            End Get
            Set
                Me.createTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property UpdateTime() As String
            Get
                Return Me.updateTimeField
            End Get
            Set
                Me.updateTimeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExtractingCodeInfoDetailData() As ExtractingCodeInfoDetailData
            Get
                Return Me.extractingCodeInfoDetailDataField
            End Get
            Set
                Me.extractingCodeInfoDetailDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.5494"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ExtractingCodeInfoResponse
        
        Private codeMsgField As CodeMsg
        
        Private extractingCodeInfoDataField As ExtractingCodeInfoData
        
        '''<remarks/>
        Public Property CodeMsg() As CodeMsg
            Get
                Return Me.codeMsgField
            End Get
            Set
                Me.codeMsgField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ExtractingCodeInfoData() As ExtractingCodeInfoData
            Get
                Return Me.extractingCodeInfoDataField
            End Get
            Set
                Me.extractingCodeInfoDataField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub HelloWorldCompletedEventHandler(ByVal sender As Object, ByVal e As HelloWorldCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HelloWorldCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub QueryExtractingCodeInfoCompletedEventHandler(ByVal sender As Object, ByVal e As QueryExtractingCodeInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class QueryExtractingCodeInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ExtractingCodeInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ExtractingCodeInfoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub QueryExtractingCodeInfoTestCompletedEventHandler(ByVal sender As Object, ByVal e As QueryExtractingCodeInfoTestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class QueryExtractingCodeInfoTestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ExtractingCodeInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ExtractingCodeInfoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub SetExtractingCodeStatusCompletedEventHandler(ByVal sender As Object, ByVal e As SetExtractingCodeStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SetExtractingCodeStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CodeMsg
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CodeMsg)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub SetExtractingCodeUsedUpdateStatusCompletedEventHandler(ByVal sender As Object, ByVal e As SetExtractingCodeUsedUpdateStatusCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SetExtractingCodeUsedUpdateStatusCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CodeMsg
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CodeMsg)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub QueryOrderAllInfoCompletedEventHandler(ByVal sender As Object, ByVal e As QueryOrderAllInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class QueryOrderAllInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OrderAllInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OrderAllInfoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub QueryOrderAllInfoTestCompletedEventHandler(ByVal sender As Object, ByVal e As QueryOrderAllInfoTestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class QueryOrderAllInfoTestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OrderAllInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OrderAllInfoResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483")>  _
    Public Delegate Sub TestRequestCompletedEventHandler(ByVal sender As Object, ByVal e As TestRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.5483"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TestRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As OrderAllInfoResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),OrderAllInfoResponse)
            End Get
        End Property
    End Class
End Namespace
