'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8762
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ShoppingCardSystem.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property Area() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Area", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BatchCharge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatchCharge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BatchChargeHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatchChargeHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BatchChargeSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatchChargeSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Bonus() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bonus", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BonusHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BonusHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BonusReporting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BonusReporting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BonusReportingHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BonusReportingHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BonusReportingSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BonusReportingSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BonusSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BonusSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BusinessType() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BusinessType", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BusinessTypeHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BusinessTypeHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BusinessTypeSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BusinessTypeSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CarrefourLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CarrefourLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CashActivation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CashActivation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CashActivationHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CashActivationHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CashActivationSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CashActivationSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChequeActivation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChequeActivation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChequeActivationHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChequeActivationHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ChequeActivationSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ChequeActivationSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CityDiscountRule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CityDiscountRule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CityDiscountRuleHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CityDiscountRuleHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CityDiscountRuleSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CityDiscountRuleSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CloseShortKeys() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CloseShortKeys", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CobrandCard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CobrandCard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CobrandCardHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CobrandCardHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CobrandCardSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CobrandCardSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ContractManagement() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ContractManagement", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ContractManagementHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ContractManagementHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ContractManagementSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ContractManagementSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CrossContractManagement() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CrossContractManagement", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CrossContractManagementHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CrossContractManagementHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CrossContractManagementSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CrossContractManagementSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CrossSelling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CrossSelling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CrossSellingCityDiscountRule() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CrossSellingCityDiscountRule", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CrossSellingCityDiscountRuleHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CrossSellingCityDiscountRuleHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CrossSellingCityDiscountRuleSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CrossSellingCityDiscountRuleSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CrossSellingHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CrossSellingHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CrossSellingSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CrossSellingSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CULElcSpecialOperation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CULElcSpecialOperation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CULElcSpecialOperationHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CULElcSpecialOperationHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CULElcSpecialOperationSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CULElcSpecialOperationSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CULReports() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CULReports", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CULReportsHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CULReportsHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CULReportsSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CULReportsSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CULSpecialOperation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CULSpecialOperation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CULSpecialOperationHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CULSpecialOperationHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CULSpecialOperationSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CULSpecialOperationSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Customer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Customer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CustomerHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CustomerHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CustomerSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CustomerSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CustomExport() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CustomExport", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CustomExportHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CustomExportHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property CustomExportSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CustomExportSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ECardInvoice() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ECardInvoice", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ECardInvoiceHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ECardInvoiceHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ECardInvoiceSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ECardInvoiceSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ElectronicCard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ElectronicCard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ElectronicCardHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ElectronicCardHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ElectronicCardSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ElectronicCardSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EmployeeActivation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmployeeActivation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EmployeeActivationHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmployeeActivationHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EmployeeActivationSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmployeeActivationSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EmployeeQuota() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmployeeQuota", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EmployeeQuotaHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmployeeQuotaHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EmployeeQuotaSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmployeeQuotaSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EmployeeSales() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmployeeSales", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EmployeeSalesHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmployeeSalesHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property EmployeeSalesSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("EmployeeSalesSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InvoiceItem() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InvoiceItem", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InvoiceItemHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InvoiceItemHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InvoiceItemSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InvoiceItemSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InvoiceLayout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InvoiceLayout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InvoiceLayoutHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InvoiceLayoutHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property InvoiceLayoutSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("InvoiceLayoutSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JVReporting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JVReporting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JVReportingHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JVReportingHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property JVReportingSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JVReportingSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Location() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Location", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LocationHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LocationHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LocationSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LocationSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MarketingPromotion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarketingPromotion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MarketingPromotionHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarketingPromotionHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property MarketingPromotionSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MarketingPromotionSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NewCustomer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NewCustomer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OfflineCardTaking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OfflineCardTaking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OfflineCardTakingHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OfflineCardTakingHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OfflineCardTakingSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OfflineCardTakingSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OpenContract() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenContract", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OpenCustomer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OpenCustomer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PaperCardCharge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaperCardCharge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PaperCardChargeHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaperCardChargeHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PaperCardChargeSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaperCardChargeSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PaperCardQuery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaperCardQuery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PaperCardQueryHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaperCardQueryHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PaperCardQuerySelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaperCardQuerySelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PaymentDown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaymentDown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PaymentUp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PaymentUp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Position() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Position", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PositionHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PositionHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PositionSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PositionSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PRCard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRCard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PRCardHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRCardHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PRCardSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRCardSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PredefineFaceValue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PredefineFaceValue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PredefineFaceValueHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PredefineFaceValueHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PredefineFaceValueSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PredefineFaceValueSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PWStrength0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PWStrength0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PWStrength1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PWStrength1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PWStrength2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PWStrength2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PWStrength3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PWStrength3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property PWStrength4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PWStrength4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Question() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Question", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReturnGoods() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReturnGoods", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReturnGoodsHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReturnGoodsHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ReturnGoodsSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ReturnGoodsSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Role() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Role", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SalesReporting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SalesReporting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SalesReportingHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SalesReportingHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SalesReportingSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SalesReportingSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SCLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Selling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Selling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SellingHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SellingHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SellingSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SellingSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignCardSelling() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignCardSelling", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignCardSellingHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignCardSellingHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignCardSellingSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignCardSellingSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignCardSpecialOperation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignCardSpecialOperation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignCardSpecialOperationHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignCardSpecialOperationHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SignCardSpecialOperationSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SignCardSpecialOperationSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Stopped() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Stopped", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property TrainingMode() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrainingMode", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UserManagemeHover() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UserManagemeHover", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UserManagement() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UserManagement", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property UserManagementSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UserManagementSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
